"""add reminded_at to tasks

Revision ID: 7033cb28e843
Revises: 4014d474ec54
Create Date: 2026-10-01 16:23:11.662521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7033cb28e843'
down_revision: Union[str, Sequence[str], None] = '4014d474ec54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_tasks_due_pending', 'tasks', ['due_date'], unique=False, postgresql_where=sa.text('reminded_at IS NULL AND deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_due_pending', table_name='tasks', postgresql_where=sa.text('reminded_at IS NULL AND deleted_at IS NULL'))
    op.drop_column('tasks', 'reminded_at')
    # ### end Alembic commands ###
